//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishermanSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boat
    {
        public Boat(string boat_name, DateTime expire_date, int engine_fuel_consumption)
        {
            this.boat_name = boat_name;
            this.expire_date = expire_date;
            this.engine_fuel_consumption = engine_fuel_consumption;
        }

        public int register_id { get; set; }
        public string boat_name { get; set; }
        public System.DateTime expire_date { get; set; }
        public int engine_fuel_consumption { get; set; }
        public int id { get; set; }
    
        public virtual User User { get; set; }
    }
}
